services:
  - type: web
    name: flowerbelle-system
    env: static
    buildCommand: cd frontend/flowerbelle-frontend && npm install && npm run build
    staticPublishPath: ./frontend/flowerbelle-frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html